services:
  ptlabel:
    image: ghcr.io/chasecee/brother-pt-pi:latest
    container_name: ptlabel
    pull_policy: always
    restart: unless-stopped
    ports:
      - "5000:5000"
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /sys/bus/usb/devices:/sys/bus/usb/devices
      - ./data:/app/data
    environment:
      CHAIN_PRINT: /usr/local/bin/chain-print
      PTLABEL_DATA_DIR: /app/data
