#ifndef PTLABEL_PROTOCOL_H
#define PTLABEL_PROTOCOL_H

#define PTLABEL_PORT_TUNNEL 9100
#define PTLABEL_PORT_ADMIN 8080
#define PTLABEL_STATUS_PACKET_BYTES 32
#define PTLABEL_PRINTER_VID 0x04F9
#define PTLABEL_PRINTER_PID_PT_P710BT 0x20AF
#define PTLABEL_MDNS_SERVICE "_ptlabel-bridge._tcp.local."

#endif
